name: XAI
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.22.4
  - pandas=1.4.2
  - notebook=6.4.12
  - scikit-learn=1.1.1
  - matplotlib=3.5.2
  - seaborn=0.11.2
  - shapely=1.8.2
  - lime=0.2.0.1
  - shap=0.41.0
  - scipy=1.8.1
  - imbalanced-learn=0.9.1
  - statsmodels=0.13.2